#Tomcat
server:
  port: 8233
  tomcat:
    uri-encoding: UTF-8
    min-spare-threads: 30
    max-threads: 1000
    max-connections: 10000
  servlet:
    context-path: /

#Jackson
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #Redis
  redis:
    host: localhost
    password:
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-idle: 10
        max-wait: -1ms
        max-active: 1000
        min-idle: 5
  #Mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.241/dandelion?useUnicode=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8&serverTimezone=UTC
    password: Zt123456
    username: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


#Mybatis
mabatis:
  type-aliases-package: com.zt.pugongyingapi.mapper
  mapper-locations:classpath*: /mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 200